### ISSUE TITLE
Adding milestone error

### ISSUE THREAD

**Issue by poxtihc** [Coren/redmine_advanced_roadmap_v2#18]
Hi, when adding a new milestone, multiple table heades appears...
Is it correct? I'm using Redmine 2.3.0
![add_milestone_error](https://cloud.githubusercontent.com/assets/7653000/5537482/c452c0a6-8aa2-11e4-851b-9aff6e0dad17.png)

Thanks!

**Comment by Coren** [comment]
Does this still happens ? I am not able to reproduce this one.
