### ISSUE TITLE
Error 500 when click detail issue

### ISSUE THREAD

**Issue by dawnblack2** [Coren/redmine_advanced_roadmap_v2#19]
DEPRECATION WARNING: Passing a template handler in the template name is deprecated. You can simply remove the handler name or pass render :handlers => [:erb] instead. (called from block in render_on at /var/www/redmine-2.3/lib/redmine/hook.rb:111)
  Rendered plugins/redmine_didyoumean/app/views/issues/_didyoumean_injected.html.erb (1331.6ms)
  Rendered issues/_form.html.erb (1474.2ms)
  Rendered issues/_edit.html.erb (1486.1ms)
  Rendered issues/show.html.erb within layouts/base (1956.4ms)
Completed 500 Internal Server Error in 2133ms

ActionView::Template::Error (undefined local variable or method `issues_didyoumean_event_type' for #<#<Class:0x007f4b3d02f690>:0x007f4b3d02dbd8>):
    19:   };
    20: </script>
    21: 
    22: <%= javascript_tag "observeIssueSubjectField('#{@project.id}', #{@issue.id or '\'\''}, '#{issues_didyoumean_event_type}');" %>
  lib/redmine/hook.rb:111:in`block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in`call_hook'
  app/views/issues/_form.html.erb:44:in `block in _app_views_issues__form_html_erb___4010127409761566408_69980560480920'
  app/helpers/application_helper.rb:955:in`labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___4010127409761566408_69980560480920'
  app/views/issues/_edit.html.erb:8:in`block in _app_views_issues__edit_html_erb__2388433069155645885_69980560350460'
  app/helpers/application_helper.rb:948:in `labelled_form_for'
  app/views/issues/_edit.html.erb:1:in`_app_views_issues__edit_html_erb__2388433069155645885_69980560350460'
  app/views/issues/show.html.erb:132:in `_app_views_issues_show_html_erb___4209799514191703761_69980561649240'
  app/controllers/issues_controller.rb:119:in`block (2 levels) in show'
  app/controllers/issues_controller.rb:116:in `show'

Environment:
  Redmine version                2.3.4.stable.13139
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  contracts                      1.2.0
  recurring_tasks                1.3.0
  redmine_admin_monitor          1.0.0
  redmine_ckeditor               1.0.16
  redmine_close_button           0.0.8
  redmine_contacts               3.4.1
  redmine_custom_css             0.1.4
  redmine_daily_status           0.0.1
  redmine_dashboard              2.2.2
  redmine_default_assign         0.4
  redmine_didyoumean             1.2.0
  redmine_dmsf                   1.4.9 stable
  redmine_favorite_projects      1.0.1
  redmine_graphs                 0.1.0
  redmine_importer               1.2.2
  redmine_issue_checklist        2.0.5
  redmine_issue_favicon          0.0.1
  redmine_lightbox               0.0.1
  redmine_login_audit            0.1.5
  redmine_meeting_room_calendar  2.1.3
  redmine_monitoring_controlling 0.1.1
  redmine_my_roadmaps            0.1.13_redmine2.3
  redmine_pipeline_plugin        2.0.0
  redmine_questions              0.0.5
  redmine_release_notes          1.3.1
  redmine_smart_issues_sort      0.3.1
  redmine_spent_time             2.6.5
  redmine_spent_time_required    0.0.1
  redmine_timesheet_plugin       0.7.0
  redmine_update_reminder        1.0.1
  redmine_wice_grid              0.1.0
  redmine_workload               1.0.2
  redmine_xls_export             0.2.1.t6
  redmine_zenedit                0.0.2
  systango_hrm                   1.0.1
  timelog_timer                  2.0.0

**Comment by Coren** [comment]
It seems that this plugin is not compatble with "didyoumean" plugin. 
I'll check if it can be solved on this side.

**Comment by ZaLiTHkA** [comment]
I don't have any issue running this plugin along with `didyoumean`, but I also can't find any reference to `issues_didyoumean_event_type` anywhere in my Redmine's `/htdocs` folder (I looked using a regexp search in Sublime Text).

Perhaps it's something from one of the other plugins that's causing an issue? It might help if @dawnblack2 could share the file on his side where this variable is being used..

My environment is as follows:

    Environment:
      Redmine version                2.5.2.stable
      Ruby version                   2.0.0-p481 (2014-05-08) [i386-mingw32]
      Rails version                  3.2.19
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.8.8
      Git                            1.9.2
      Filesystem                     
    Redmine plugins:
      advanced_roadmap_v2            2.4.1
      collapsed_journals             0.0.2
      redmine_ckeditor               1.0.16
      redmine_didyoumean             1.2.0
      redmine_issue_checklist        2.0.5
      redmine_knowledgebase          3.0.6
      redmine_lightbox               0.0.1
      redmine_my_page_queries        2.1.6
      redmine_people                 0.1.6
      redmine_project_form_extended  0.2
      redmine_stealth                0.6.1-DEV
      redmine_tweaks                 0.4.8
      redmine_wiki_extensions        0.6.4
      redstrap                       0.0.1
      workflow_initial_status        0.0.1

**Please note:** `redstrap` is a private plugin, `redmine_stealth` is a modified version of the original.. All others are currently unmodified.

By the way @Coren, the "Releases" page on your repo here may show version a "v1.0", but the plugin's `init.rb` still defines it as `2.4.1`, hence the version listed above.

**Comment by Coren** [comment]
@ZaLiTHkA I've updated the release on github, thanks !
