### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by bluenyx** [Coren/redmine_advanced_roadmap_v2#24]
rake aborted!
NameError: undefined method `completed_pourcent' for class `Version'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
/var/www/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/version_patch.rb:15:in `block in included'
/var/www/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/version_patch.rb:6:in `class_eval'
/var/www/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/version_patch.rb:6:in `included'
/var/www/redmine/plugins/advanced_roadmap_v2/init.rb:21:in `include'
/var/www/redmine/plugins/advanced_roadmap_v2/init.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/var/www/redmine/lib/redmine/plugin.rb:155:in `block in load'
/var/www/redmine/lib/redmine/plugin.rb:146:in `each'
/var/www/redmine/lib/redmine/plugin.rb:146:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/engine.rb:648:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/notifications.rb:161:in `instrument'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/engine.rb:647:in `load_config_initializer'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/engine.rb:611:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/application.rb:276:in `require_environment!'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/railties-4.1.8/lib/rails/application.rb:389:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
------------------------------------------------------------------------------------------------
/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap$ vi version_patch.rb

 pourcent --> percent

If you modify the typos version_patch.rb being installed.

**Comment by Coren** [comment]
Thanks for your detailed report. Is this ok for you with my last commit ?
