### ISSUE TITLE
There is no Milestones tab in the Project Settings Menu

### ISSUE THREAD

**Issue by Saylrman64** [Coren/redmine_advanced_roadmap_v2#25]
Hello again,

Thank you for the response but the original issue is still not fixed.
>> There is no Milestones tab in the Project Settings Menu. I cannot Create, Edit or Delete milestones.
The latest download did create the DB table correctly and I verified Managers have Permissions on the Milestone.
Still, there is not Milestone Menu in the Project Settings. Even if logged in as Admin.

Thanks

**Comment by Coren** [comment]
If you don't see an advanced roadmap instead of Redmine default one, and you cannot access Milestones tab, even as an Admin, then it means that the plugin is not installed in your (production ?) environment. 
You should check rights, path, etc,

**Comment by Saylrman64** [comment]
Hello,

You cannot seriously close this issue just because you answered a single post question.
In previous comments I indicated that the plugin loads and I DO see the advanced Roadmap.
I just don't get the Milestones.

Thanks
