### ISSUE TITLE
manager cannot add milestone

### ISSUE THREAD

**Issue by slvr9** [Coren/redmine_advanced_roadmap_v2#27]
associated with #8
I can not add a milestone as manager (button "add" missing).
I can add milestone only as admin.

```
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p448 (2013-06-27) [i486-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.4
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.1.1
  projects_table                 0.0.4
```

**Comment by Coren** [comment]
Yes, you can. You have to assign manage_milestones permission to manager role.

BTW, I have try to set it by default during rake redmine:plugins:migrate installation step with this commit:
https://github.com/Coren/redmine_advanced_roadmap_v2/commit/4b59ac1aaeaad692bad3161af032e74742f9a438

**Comment by slvr9** [comment]
I completely reinstalled component, no results.

4b59ac1 may depend on whether the language?
`role = Role.find(:first, :conditions => "name='Manager'")`

Manager (en) -> Менеджер (ru)

**Comment by Coren** [comment]
Yes, you're right: it depend on the language. I haven't found a 100% sure way of getting it. 

So: it can set it automatically if role name is the default. If it's not, you have to set manually manage_milestones permission to "Менеджер" role by yourself.

**Comment by slvr9** [comment]
Sorry. I was blind.
Сould not find the checkBox on the page editing rights.

Thank you for your patience. Best regards.
