### ISSUE TITLE
Due Date

### ISSUE THREAD

**Issue by hwinkel** [Coren/redmine_advanced_roadmap_v2#29]
Hi, can this plugin show due dates of the referenced issues in the roadmap ?

**Comment by Coren** [comment]
Hi, 

I agree with you, this is more useful. I've implemented it with this commit  https://github.com/Coren/redmine_advanced_roadmap_v2/commit/3631c124a969c057149fe0925e39e49eef620b87 

Starting from v2.2.0, this is included and the default behavior.

If one wants the old behavior, it's been made configure-able in plugin setting.

Regards,
