### ISSUE TITLE
The error comes when I install a plugin.

### ISSUE THREAD

**Issue by bluenyx** [Coren/redmine_advanced_roadmap_v2#31]
Hello,
The error comes when I install a plugin. I do not know how to solve.

Redmine : v3.0.0

rake redmine:plugins:migrate RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
Migrating advanced_roadmap_v2 (Advanced roadmap & milestones plugin)...
== 1 CreateMilestones: migrating ==============================================
-- create_table(:milestones, {:force=>true})
   -> 0.0414s
-- add_index(:milestones, [:user_id], {:name=>"fk_milestones_user"})
   -> 0.0183s
-- add_index(:milestones, [:project_id], {:name=>"fk_milestones_project"})
   -> 0.0467s
== 1 CreateMilestones: migrated (0.1069s) =====================================

== 2 CreateMilestoneVersions: migrating =======================================
-- create_table(:milestone_versions, {:force=>true})
   -> 0.0161s
-- add_index(:milestone_versions, [:milestone_id], {:name=>"fk_milestone_versions_milestone"})
   -> 0.0197s
-- add_index(:milestone_versions, [:version_id], {:name=>"fk_milestone_versions_version"})
   -> 0.0220s
== 2 CreateMilestoneVersions: migrated (0.0582s) ==============================

== 3 PresetPermissions: migrating =============================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Couldn't find all Roles with 'id': (first, {:conditions=>"name='Manager'"}) (found 0 results, but was looking for 2)/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:336:in `raise_record_not_found_exception!

/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:479:in `find_some'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:438:in `find_with_ids'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:71:in `find'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/querying.rb:3:in `find'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/core.rb:128:in `find'
/var/www/redmine/plugins/advanced_roadmap_v2/db/migrate/003_preset_permissions.rb:3:in `up'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:569:in `up'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:609:in `exec_migration'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:446:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/var/www/redmine/lib/redmine/plugin.rb:459:in `each'
/var/www/redmine/lib/redmine/plugin.rb:459:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p451/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate

==

Was only install the current redmine, and there is no project.

Thanks.

**Comment by EricOVGU** [comment]
I have the same Problem. Redmine Version is 3.0.0 too. Any solutions?

**Comment by Coren** [comment]
This problem comes when default data was not loaded. 
This migration try to set access by default access to milestone when you are a "manager", as defined by this default data. 
=> If you did not load this default data, rights configuration is up to redmine administrator

I'll package this fix into a new release. Thanks for your report.

**Comment by EricOVGU** [comment]
first thanks for the update! The installation runs now. But now there is a problem with rails >4.0. When I open a site there is an error:

ActionView::Template::Error (The provided regular expression is using multiline anchors (^ or $), which may present a security risk. Did you mean to use \A and \z, or forgot to add the :multiline => true option?):
    1: <%- if !@project.nil? -%>
    2: <h3><%= l(:label_milestone_plural) %></h3>
    3: <%- @project.milestones.sort.each do |milestone| -%>
    4: <%= link_to_milestone(milestone) %><br />
    5: <%- end -%>
    6: <%- end -%>

I think there was a chang with ^ and $ in rails 4.

**Comment by Coren** [comment]
Hi,

This new issue will be tracked on issue #33
