### ISSUE TITLE
Error on regexp: The provided regular expression is using multiline anchors

### ISSUE THREAD

**Issue by Coren** [Coren/redmine_advanced_roadmap_v2#33]
first thanks for the update! The installation runs now. But now there is a problem with rails >4.0. When I open a site there is an error:

ActionView::Template::Error (The provided regular expression is using multiline anchors (^ or $), which may present a security risk. Did you mean to use \A and \z, or forgot to add the :multiline => true option?):
1: <%- if !@project.nil? -%>
2:
<%= l(:label_milestone_plural) %>

3: <%- @project.milestones.sort.each do |milestone| -%>
4: <%= link_to_milestone(milestone) %>

5: <%- end -%>
6: <%- end -%>

I think there was a chang with ^ and $ in rails 4.

**Comment by EricOVGU** [comment]
Works well now. Thank you!
