### ISSUE TITLE
[Feature] Order of versions

### ISSUE THREAD

**Issue by EricOVGU** [Coren/redmine_advanced_roadmap_v2#34]
Hello!
Is it possible to order the versions in the roadmap. At the moment I have for example 3 versions (15.0/16.1/17.0). When I click "Roadmap" I see this order: first 15.0, then 17.0, last 16.1.
Can this be ordered by name or date?

Best regards!

**Comment by Coren** [comment]
Hi,

I've re-tested with both redmine v2.6 or v3.0, versions in roadmap are sorted the same way as version in project's configuration. 

Order is mainly by date, then by name. That means that versions with a date alway comes first before versions without it.

Would you please re-check ?

Regards

**Comment by EricOVGU** [comment]
Hello,

thanks for testing! It seems to work this way. I can change the order by date. 

Best Regards
