### ISSUE TITLE
Inherited versions - links in roadmap

### ISSUE THREAD

**Issue by dominch** [Coren/redmine_advanced_roadmap_v2#35]
Hello 
Links on roadmap are generated for original project ID, and not for subprojects. 
When user is assinged only to subproject he can see wrong issue count (count from main project) and links to issues are generated to main project causing 403 errors 
To reproduce just create project and subproject in it, set version in project + share it into tree, then go to subproject and click on roadmap. Links are not related to subproject but for main project :(

**Comment by Coren** [comment]
Hi,

I was able to reproduce your problem. I'll see what I can do about it.

**Comment by Coren** [comment]
Behaviour is the same if you remove the plugin from Redmine. 
It seems that it comes from design of inherited version.

I'm quite sure I cannot do something about it.

**Comment by dominch** [comment]
Yes, I reported that to redmine too: 
http://www.redmine.org/issues/19187
Can any plugin correct that? maybe by option? Sometimes that is a reason for installing plugin :) 
Or is there a chance to add information from both project and subproject with info about permissions?
