### ISSUE TITLE
Questions to the forecast formulas

### ISSUE THREAD

**Issue by liomoura** [Coren/redmine_advanced_roadmap_v2#42]
Hello,

Could teach what formula is used to calculate the forecast?

![image](https://cloud.githubusercontent.com/assets/10420467/6555103/6eb07dde-c641-11e4-9b78-199d429d4d6b.png)

Thank You!

**Comment by Coren** [comment]
It's a simple forecast. 
Due in  = Estimated time - (Estimated time * % Done)

**Comment by Coren** [comment]
Maybe I have closed this issue too fast :).
In short: if you have make 10% of this issue in 10 hours, then your due time should be is 90 hours.
