### ISSUE TITLE
Only 1 set of milestones displayed in Gantt Chart

### ISSUE THREAD

**Issue by adamb03** [Coren/redmine_advanced_roadmap_v2#43]
Hello, love the plugin, the way I have our redmine configured is to have a master project. then I have subprojects.  Each subproject has their own milestones. this works great.  when I look at a subproject's gantt chart, i see the milestones, and tickets, and it all looks great.

when i look at the master project's gantt chart what i see is

![master_project_gantt](https://cloud.githubusercontent.com/assets/11426824/6600349/824fa130-c7e5-11e4-935c-a60b81b24c3e.PNG)

If i click into any subproject, I see all the milestones associated with it:

![subproject_gantt](https://cloud.githubusercontent.com/assets/11426824/6600360/8b3b45b0-c7e5-11e4-9280-61675473cd38.PNG)

Only in the master Project Gantt chart, i see only the first subprojects milestones.  How do i see the milestones for all the subprojects in the master project's gantt chart?

**Comment by adamb03** [comment]
Any updates? Is anyone actively working on this project ?

**Comment by Coren** [comment]
Yep. I've been quite busy lately, but I'll surely find some time during may.
