### ISSUE TITLE
graph & progress bar not displayed

### ISSUE THREAD

**Issue by HappyJays** [Coren/redmine_advanced_roadmap_v2#45]
![image](https://cloud.githubusercontent.com/assets/11568442/6772281/5ee1a4da-d13d-11e4-9f60-f51807a18a4b.png)

Environment:
  Redmine version                2.4.1.stable
  Ruby version                   1.9.3-p231 (2012-05-25) [i386-mingw32]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.9
  Git                            1.8.3
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.0
  openalms_traceability          1.0.0
  redmine_banner                 0.0.8
  redmine_better_gantt_chart     0.9.0
  redmine_ckeditor               1.0.16
  redmine_impasse                1.2.2
  redmine_importer               1.2.2
  redmine_issue_detailed_tabs_time 0.1.0
  redmine_issue_templates        0.0.9
  redmine_monitoring_controlling 0.1.1
  redmine_my_page_queries        2.1.6
  sidebar_hide                   0.0.7

graph & progress bar not displayed and total is displayed in 0%.
"Administration > Information > RMagick available (optional)" has also been checked.
what's the problem? 

Thank you!

**Comment by Coren** [comment]
It can only be displayed when you input your estimated time on your issues. 
Is this more clear for you ?
