### ISSUE TITLE
Total spent time is not calculated on roadmap view

### ISSUE THREAD

**Issue by sksemenov** [Coren/redmine_advanced_roadmap_v2#47]
If an issue has sub-tasks with spent time logged it appears on the roadmap view with 0 time spent (that is not correct).

![image](https://cloud.githubusercontent.com/assets/6285758/7252891/485d1620-e841-11e4-8de7-5f72bfa5729a.png)

**Comment by jhb92** [comment]
if version name is chinese and then time tracking of Roadmap show chinese ????。
