### ISSUE TITLE
Associate a shared versions to Milestone

### ISSUE THREAD

**Issue by lucafrosini** [Coren/redmine_advanced_roadmap_v2#49]
I have two project , one (A) is the child of the other (B).
I have shared versions between projects and an A I can see the versions of B and viceversa, but I can't associate a version of B in a milestone of project A (and viceversa).

Is this a feature or a bug? If it is a feature can you suggest me where to change the behaviour? Maybe is just a matter of db query?

**Comment by Coren** [comment]
It's neither a feature or a bug. 

I didn't think one would want to share versions AND milestones between a project and its sub.

It's not implemented at the moment. It's a matter of source code, not db query.

**Comment by lucafrosini** [comment]
Thanks for your prompt reply
