### ISSUE TITLE
[Feature Request] Creating a filter for situation "closed" or "open"

### ISSUE THREAD

**Issue by liomoura** [Coren/redmine_advanced_roadmap_v2#50]
Creating a filter for situation "closed" or "open"

**Comment by Coren** [comment]
Hi, my last commit d0a82e8c3bfbb05d88b2e8142ec9e0db2368aaaa is a step forward a filter for "open" or "closed" filter.

What do you think about it ?

Regards

**Comment by liomoura** [comment]
Thank you!
