### ISSUE TITLE
404 when creating milestone

### ISSUE THREAD

**Issue by vakorol** [Coren/redmine_advanced_roadmap_v2#52]
Redmine v.3.0.3
Advanced Roadmap Plugin v.2.4.1
No other plugins are present.

- navigate to projects->settings->milestones
- click "(+) new milstone"
- fill the name, click "create"

In response i get a 404 page, and the folowing lines appear in the logfile:
<pre>
App 10618 stderr: Started POST "/redmine/projects/viking/milestones" for 127.0.0.1 at 2015-05-26 15:00:51 +0200
App 10618 stderr: Processing by MilestonesController#create as HTML
App 10618 stderr:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"9k6tQfbnTUCScaF6HwZ0RQfndIylHGqdO38KSM7YyIpGIUrfvHfpCCw+5KUY+s0p86H5RwodfGWSE7Vn4/sbQA==", "milestone"=>{"name"=>"Implement a basic viewer..", "description"=>"", "effective_date"=>""}, "commit"=>"Create", "project_id"=>"viking"}
App 10618 stderr:   Current user: vakorol (id=5)
App 10618 stderr: Missing template, responding with 404
App 10618 stderr:   Rendered common/error.html.erb within layouts/base (0.2ms)
App 10618 stderr:   Rendered plugins/advanced_roadmap_v2/app/views/hooks/_stylesheet.html.erb (0.2ms)
App 10618 stderr: Completed 404 Not Found in 173ms (Views: 11.1ms | ActiveRecord: 3.2ms)
</pre>

**Comment by Coren** [comment]
I didn't manage to reproduce your problem, with Redmine 3.0.3, 3.0.0 or 2.6.0.

I reinstalled, config a new db, set a new secret token, create a new project, go settings->milestones on this project

Can you check 
1) Plugin is in `plugins/advanced_roadmap_v2`
2) Re-run this command 
```bash
  bundle exec rake redmine:plugins:migrate
```

**Comment by vakorol** [comment]
Somehow re-running the migration worked!
Thanks for help.
