### ISSUE TITLE
500 error upon git clone installation.

### ISSUE THREAD

**Issue by shawndibble** [Coren/redmine_advanced_roadmap_v2#54]
Tried installing your plugin. After restarting apache, I get a 500 error immediately. Below is a copy of the production.log file. updated 6/23/2015

Started GET "/admin" for 192.168.1.58 at 2015-06-23 16:04:27 -0500
Processing by AdminController#index as HTML
  Current user: *******(id=320)
  Rendered admin/_menu.html.erb (4.8ms)
  Rendered admin/index.html.erb within layouts/admin (6.1ms)
  Rendered layouts/base.html.erb (8.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 500 Internal Server Error in 39ms (ActiveRecord: 0.6ms)

ActionView::Template::Error (Missing partial hooks/_stylesheet with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "/var/data/redmine/plugins/redmine_monitoring_controlling/app/views"
  * "/var/data/redmine/plugins/redmine_ldap_sync/app/views"
  * "/var/data/redmine/plugins/redmine_importer/app/views"
  * "/var/data/redmine/plugins/redmine_ckeditor/app/views"
  * "/var/data/redmine/plugins/redmine_checklists/app/views"
  * "/var/data/redmine/plugins/redmine_bootstrap_kit/app/views"
  * "/var/data/redmine/plugins/redmine_agile/app/views"
  * "/var/data/redmine/app/views"
  * "/usr/local/rvm/gems/ruby-2.0.0-p643/gems/kaminari-0.16.3/app/views"
  * "/usr/local/rvm/gems/ruby-2.0.0-p643/bundler/gems/rich-93d1dd9526e1/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: 
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb__4553804919593994518_48302540'
  app/controllers/application_controller.rb:469:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:467:in `render_error'
  app/controllers/application_controller.rb:455:in `render_404'
  app/controllers/application_controller.rb:479:in `missing_template'

**Comment by zealot128** [comment]
ran into the same issue, fixed it with renaming the plugin folder to:

```
plugins/advanced_roadmap_v2
```

explaination: the folder have to have to the same name as the plugin, otherwise the view paths are not found.

**Comment by Coren** [comment]
I can confirm this. 
You need to rename your plugin folder to 
```
plugins/advanced_roadmap_v2
```

**Comment by shawndibble** [comment]
Yep. I was just doing a git clone like I do with all the other redmine plugins. Helps if I follow directions.
