### ISSUE TITLE
View estimated hours permission problem and not useful

### ISSUE THREAD

**Issue by BRUTEF0RCE** [Coren/redmine_advanced_roadmap_v2#56]
Good day! First I want to thank you for this great plugin! :)  

Second, I noticed a problem with the estimated hours view permission;  Let say I have an issue with 10.0 hours as estimated time.  I am a developer, I have the view rights on estimated time and I am the one who entered this 10.0 hours estimate. No problem yet.  Now let say that user Bob which has the role "Client" in the project (and "client" do not have the view rights on estimated hours) edit the issue and add a note to it, Bob will still see the estimate time edit box but it will be empty.  bob does not touch this edit box, only write a note in the issue and save it.  Now, when any user (who has the right to view estimated hours) access this issue, the estimated time field will not be present (as if the 10.0 hours was deleted from this box).  But there are no mention in the historical notes of the issue that anyone has deleted the estimated time! It is deleted but with no mention of deletion in the notes!  My actual work around, I give all roles the view estimated hour rights, which means I do not use this permission at all for now.  

Third, I mention "not useful" in the title because even if the user does not have the right to view estimated hours, he can still see it in the issue historical notes : "Estimated time set to 10.0".

Here are my Redmine versions : 

Environment:
  Redmine version                3.0.2.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [i386-mingw32]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.1
  clipboard_image_paste          1.10
  issuefy                        0.2.0
  localizable                    0.3.0
  progressive_projects_list      2.0.1
  redmine_banner                 0.1.1
  redmine_base_deface            0.0.1
  redmine_checklists             3.1.1
  redmine_ckeditor               1.1.0
  redmine_code_review            0.7.0
  redmine_dashboard              2.5.0
  redmine_didyoumean             1.2.0
  redmine_documents_short        0.3.0
  redmine_helpdesk               0.0.14
  redmine_ics_export             3.0.1.dev
  redmine_issue_favicon          0.0.1
  redmine_lightbox2              0.2.2
  redmine_local_avatars          0.2.0
  redmine_mail_reminder          3.0.0.0001
  redmine_maintenance_mode       2.0.1
  redmine_my_page                0.1.4
  redmine_per_project_formatting 0.0.4
  redmine_silencer               0.4.0
  redmine_wktime                 1.8.1
  redmine_xlsx_format_issue_exporter 0.1.2
  sidebar_hide                   0.0.7

Thank you again.

  Thierry

**Comment by Coren** [comment]
Hi,

Thanks for your support and your detailed issue.

I did not manage to clearly reproduce your issue.

If one *can* edit issue, then yes, he will be able to change estimated time. And he will see current estimated time in the field.

If one *cannot* edit issue and does not have any rights about estimated time, he won't see anything at all about this matter and won't be able to modify it. He'll just be able to add a note.

**Comment by arcanemartz** [comment]
Hi,

I think the feature is broken (at least on redmine 3.1 here).  If someone doesn't have the right to view the estimated time (but can edit the issue, but this is irrelevant i'd say), he will not see the estimated time edit box, but will see any previous changes made to the estimated time in the journals.

AdvancedRoadmap::IssuesControllerPatch is for sure not working with redmine 3.1 (and probably 3.0 also).

I'll try to submit a pull request later with the change I made here to have the estimated time logs hidden when the user doesn't have the right to view estimated time.

Regards,
Martin

**Comment by arcanemartz** [comment]
3715ec83ceb0c5114a97fc15f369312cc4d4d468 fixes the issue here.

**Comment by Coren** [comment]
I don't know how you submit your fix, so I had to re-write your fix. 

It's applied.  Thanks.
