### ISSUE TITLE
show/hide columns in related issue list

### ISSUE THREAD

**Issue by salem-san** [Coren/redmine_advanced_roadmap_v2#59]
it will be good if we can change issues table columns.
for example, i dont use categories, i dont need this to be shown on my issues list roadmap

(French)
ça serai génial si on pouvais configurer les colonnes du tableau des demandes liées (issues).
par exemple, je n'utilise pas la notion des catégories pour mes demandes, donc j'aurais pas besoin que ça serai affiché dans le tableau.
merci.

**Comment by Coren** [comment]
Would you please test last git version ? 
It will detect if you use category and don't display "category" column if it's not used.
