### ISSUE TITLE
Subtask issue with parent task which have different target versions do not show up in the roadmap target version related issue list

### ISSUE THREAD

**Issue by BRUTEF0RCE** [Coren/redmine_advanced_roadmap_v2#61]
Subtask issue 2 (assigned to target version A) with parent task issue 1 which have a different target version B (or no target version assigned) do not show up in the roadmap target version "related issue" list of target version A !  I removed the plugin from my Redmine installation and the related issue list of target version A is properly populated with the subtask issue 2 in it.  The problem only appear when using this plugin.  Can you reproduce and do you think there could be a fix to this?

Thank you.

**Comment by BRUTEF0RCE** [comment]
The total calculated percentage done of all listed issue in the version seems odd as well.  I have a situation here where only the child task is in the roadmap version without the parent task being present. Does that mess up your way of calculating the percentage of all listed issue?

**Comment by Coren** [comment]
Hi, 

Your use case seems quite weird to me. 

Anyway, I've tried to fix it. 

Would you please tell me if it's better for you, now ?

Regards,

**Comment by BRUTEF0RCE** [comment]
Good day, the problem is still present.  Please note that the parent task need to not be part of the roadmap version for the problem to arise.  Please also note that a similar problem is signalled on the original version of this plugin.

  See : https://redmine.ociotec.com/issues/1109

Thank you for your time!

Regards
