### ISSUE TITLE
Redmine 3.2

### ISSUE THREAD

**Issue by marcoprodata** [Coren/redmine_advanced_roadmap_v2#64]
This plugin will be updated to work with Redmine 3.2?

**Comment by Coren** [comment]
Yes, and it will be done this week, if possible

**Comment by mlabate** [comment]
Hi, on redmine 3.2 I got an "Internal error" after plugin installation. Is it still not compatible with 3.2?
Thanks

**Comment by PhilJung** [comment]
For info, git clone of the plugin does not work under Redmine 3.2 but if you rename the redmine_advanced_roadmap_v2 folder to advanced_roadmap_v2, then it seems to work.

**Comment by Coren** [comment]
There's no issue with redmine 3.2. I'll just update information on redmine website.
