### ISSUE TITLE
How to uninstall/reinstall the plugin?

### ISSUE THREAD

**Issue by LeGiangAnh** [Coren/redmine_advanced_roadmap_v2#69]
Hi,

I have one problem while trying to uninstall the plugin follow Redmine official guideline.
My Redmine show internal error after I migrated database and remove the files. I cannot use Redmine anymore.
Could you please add the the Uninstall/reinstall and update sections to guideline?

**Comment by Xflofoxx** [comment]
Hi, 
I also have the same problem.
Thanks
