### ISSUE TITLE
Can CJK font be supported

### ISSUE THREAD

**Issue by cityant** [Coren/redmine_advanced_roadmap_v2#73]
First great thanks for the plugin. It's very helpful for us.

We have some projects using Chinese in versions, the problem is that Chinese chars in legend labels in the pie chat shows '???'. 

My question is, can the plugin support font file be configured and rmagic can use it? Or can the plugin use the settings of Redmine configuration.yml, rmagick_font_path?

Thanks a lot.

**Comment by Coren** [comment]
Hi,

Thanks for this info. I've tried to enhance the code in order to use Redmine configuration, with this rmaigck_font_path, into my last commit [047e960](https://github.com/Coren/redmine_advanced_roadmap_v2/commit/047e96012fb6a687fa5d8a50566675865c58031c)

Would you please test it ?

Regards,

**Comment by cityant** [comment]
It works! Thanks again!

**Comment by archonwang** [comment]
Gets OK，Thanks.

there is the steps as follows:

1. in [redmine]/config,
# vi configuration.yml
found  rmaigck_font_path and fill with the examples
2. restart redmine and it works.
