### ISSUE TITLE
Wrong issue parents on the Roadmap page

### ISSUE THREAD

**Issue by vakorol** [Coren/redmine_advanced_roadmap_v2#77]
I have noticed that some of the tasks are displayed under wrong parents on the "Roadmap" tab of my project in Redmine.

Here is how the issue page looks like. Note the correct parent id:

![task769-descr](https://cloud.githubusercontent.com/assets/1204343/15500876/10b6b272-21ab-11e6-8545-b1876b4dad1a.jpg)

But on the "Roadmap" page the issue is shown under a different (and totally unrelated) 'parent':

![roadmap](https://cloud.githubusercontent.com/assets/1204343/15500845/ed0e2454-21aa-11e6-83b9-39dbf3424f21.jpg)

```
Environment:
  Redmine version                3.2.2.stable
  Ruby version                   2.0.0-p384 (2014-01-12) [x86_64-linux-gnu]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  advanced_roadmap_v2            2.4.2
```

**Comment by Coren** [comment]
won't fix

**Comment by vakorol** [comment]
May i ask why? Is it not doable, or is the issue not relevant to the plugin?

**Comment by vakorol** [comment]
okay, i see, the plugin will not be maintained anymore.
