### ISSUE TITLE
total calculation is zero

### ISSUE THREAD

**Issue by jeacott1** [Coren/redmine_advanced_roadmap_v2#78]
![image](https://cloud.githubusercontent.com/assets/16600100/15744853/b5a8b82a-290d-11e6-9a92-33e00e4ce62f.png)

![image](https://cloud.githubusercontent.com/assets/16600100/15744924/1b9f0ef4-290e-11e6-922d-db60bf40d3df.png)

  Redmine version                3.0.3.stable.14369
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  4.2.2
  Environment                    production

Redmine plugins:
  advanced_roadmap_v2            2.4.3
  clipboard_image_paste          1.10
  progressive_projects_list      3.0.1
  redmine_agile                  1.4.0
  redmine_code_review            0.7.0
  redmine_lightbox2              0.2.5
  redmine_scm                    0.5.1
  redmine_slack                  0.1
  redmine_tags                   3.1.1
  redmine_theme_changer          0.2.0
  redmine_wiki_extensions        0.7.0

no errors in the log, a few NaN though. 

Started GET "/milestones/total_graph?percentajes%5B%5D=NaN&percentajes%5B%5D=NaN&size=500x400&versions%5B%5D=50k+v1.0.0&versions%5B%5D=50k+v1.1.0" for 14.2.45.39 at 2016-06-02 08:33:32 -0400
Processing by MilestonesController#total_graph as HTML
  Parameters: {"percentajes"=>["NaN", "NaN"], "size"=>"500x400", "versions"=>["50k v1.0.0", "50k v1.1.0"]}
  Current user: jxxxx (id=6)
  Rendered text template (0.0ms)
Sent data  (1.5ms)
Completed 200 OK in 93ms (Views: 1.1ms | ActiveRecord: 0.3ms)

**Comment by Coren** [comment]
won't fix
