### ISSUE TITLE
manager cannot add milestone

### ISSUE THREAD

**Issue by slvr9** [Coren/redmine_advanced_roadmap_v2#8]
I can not add a milestone as _manager_ (button "add" missing).
I can add milestone only as _admin_.

**Comment by Saylrman64** [comment]
Hello again,

Thank you for the response but the original issue is still not fixed.
>> There is no Milestones tab in the Project Settings Menu. I cannot Create, Edit or Delete milestones.
The latest download did create the DB table correctly and I verified Managers have Permissions on the Milestone.
Still, there is not Milestone Menu in the Project Settings. Even if logged in as Admin.

Thanks
