### ISSUE TITLE
Comparison of This Fork to Original Project

### ISSUE THREAD

**Issue by johnzimm** [Coren/redmine_advanced_roadmap_v2#80]
I'm looking over the advanced_roadmap projects right now and notice the original and this fork are both active relatively recently.

Can you elaborate on what the primary differences are at this point?

**Comment by Coren** [comment]
There is no major differences. I just forked because I need it and the original was not working on current versions of redmine.

Since the original is back on rails, I'll stop here the maintenance of this plugin.
