### ISSUE TITLE
when I add milestone, I do not see the names of sub projects.

### ISSUE THREAD

**Issue by slvr9** [Coren/redmine_advanced_roadmap_v2#9]
when I add milestone, I do not see the names of sub projects.

![redmine__advanced_roadmap_v2__bug00](https://cloud.githubusercontent.com/assets/394362/5312271/4de1154a-7c78-11e4-98c6-2c331ef43da0.png)

**Comment by sbert** [comment]
I've got the same problem.

**Comment by Coren** [comment]
Thanks for your patch !
